apiVersion: v1
kind: Service
metadata:
  name: my-helloworld-rs-svc
spec:
  selector:
    app: my-helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
# 1 Line Command
# kubectl expose rs my-helloworld-rs  --type=NodePort --port=80 --target-port=8080 --name=my-helloworld-rs-service
